FROM ubuntu:latest

WORKDIR /build

RUN apt-get update && \
    apt-get install -y \
      build-essential \
      autoconf \
      automake \
      autotools-dev \
      autopoint \
      libtool \
      pkg-config \
      libssl-dev \
      libgnutls28-dev \
      libc-ares-dev \
      zlib1g-dev \
      libsqlite3-dev \
      libssh2-1-dev \
      gettext \
      git

COPY . /build

RUN autoreconf -i && \
    ./configure \
      --prefix=/usr/local \
      --with-openssl \
      --without-gnutls && \
    make -j$(nproc) && \
    make install

FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
      libssl3 \
      libgnutls30 \
      libc-ares2 \
      zlib1g \
      libsqlite3-0 \
      libssh2-1 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=0 /usr/local/bin/aria2c /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/aria2c"]
